# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        /:categories/:title

# Setup
title:            Post Tenabras Lux
tagline:          'After darkness light'
description:      'Open source by Kyle Hornberg'
url:              http://khornberg.github.io

author:
  name:           'Kyle Hornberg'
  url:            http://khornberg.github.io

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/khornberg

logo:             site-logo.png
quote:            By perseverance the snail made it to the ark. -- Charles Spurgeon
